import {
  Merge,
  Split,
  Copy,
  Trash2,
  ArrowUpDown,
  RotateCw,
  Crop,
  Files,
  FileText,
  FileSpreadsheet,
  Presentation,
  Image,
  FileImage,
  FileUp,
  Table,
  SlidersHorizontal,
  Upload,
  Globe,
  Minimize2,
  Wrench,
  Layers,
  Archive,
  Type,
  Edit3,
  ImagePlus,
  PenTool,
  Highlighter,
  MessageSquare,
  Square,
  Stamp,
  Hash,
  PanelTop,
  Lock,
  Unlock,
  EyeOff,
  ShieldAlert,
  FileCheck2,
  CheckSquare,
  PenLine,
  Send,
  FolderKanban,
  Sparkles,
  ShieldCheck,
} from 'lucide-react';

export const CATEGORIES = [
  {
    id: 'organize',
    name: 'Organize',
    icon: FolderKanban,
    color: 'text-indigo-500 dark:text-indigo-400',
    bgColor: 'bg-indigo-50 dark:bg-indigo-950/50',
    tools: [
      {
        id: 'merge-pdf',
        name: 'Merge PDF',
        title: 'Merge PDF',
        path: '/merge-pdf',
        icon: Merge,
        desc: 'Combine multiple PDF files into one unified document in your exact order.',
        category: 'Organize',
        action: 'merge',
        requiresDoc: false,
        prompt: 'Combine and merge multiple PDF files into one document.',
      },
      {
        id: 'split-pdf',
        name: 'Split PDF',
        title: 'Split PDF',
        path: '/split-pdf',
        icon: Split,
        desc: 'Separate PDF pages or extract page ranges into individual documents.',
        category: 'Organize',
        action: 'split',
        requiresDoc: true,
        prompt: 'Split this PDF document into separate files by page range.',
      },
      {
        id: 'extract-pdf-pages',
        name: 'Extract pages',
        title: 'Extract PDF Pages',
        path: '/extract-pdf-pages',
        icon: Copy,
        desc: 'Select and export specific pages from your PDF into a brand new file.',
        category: 'Organize',
        action: 'extract_pages',
        requiresDoc: true,
        prompt: 'Extract selected pages from this PDF file.',
      },
      {
        id: 'remove-pages',
        name: 'Remove pages',
        title: 'Remove Pages from PDF',
        path: '/remove-pages',
        icon: Trash2,
        desc: 'Remove unwanted, blank, or duplicate pages quickly from your PDF document.',
        category: 'Organize',
        action: 'delete_pages',
        requiresDoc: true,
        prompt: 'Remove unwanted pages from this PDF file.',
      },
      {
        id: 'reorder-pdf-pages',
        name: 'Reorder pages',
        title: 'Reorder PDF Pages',
        path: '/reorder-pdf-pages',
        icon: ArrowUpDown,
        desc: 'Drag, drop, and rearrange the sequence of pages in your PDF document.',
        category: 'Organize',
        action: 'reorder_pages',
        requiresDoc: true,
        prompt: 'Reorder and reorganize the pages of this document.',
      },
      {
        id: 'rotate-pdf-pages',
        name: 'Rotate pages',
        title: 'Rotate PDF Pages',
        path: '/rotate-pdf-pages',
        icon: RotateCw,
        desc: 'Rotate portrait and landscape PDF pages 90°, 180°, or 270° permanently.',
        category: 'Organize',
        action: 'rotate_pages',
        requiresDoc: true,
        prompt: 'Rotate pages in this PDF document to the correct orientation.',
      },
      {
        id: 'crop-pdf',
        name: 'Crop pages',
        title: 'Crop PDF Pages',
        path: '/crop-pdf',
        icon: Crop,
        desc: 'Trim margins, crop document areas, and adjust visible page boundaries.',
        category: 'Organize',
        action: 'crop_pages',
        requiresDoc: true,
        prompt: 'Crop the page margins and content area of this PDF.',
      },
      {
        id: 'duplicate-pdf-pages',
        name: 'Duplicate pages',
        title: 'Duplicate PDF Pages',
        path: '/duplicate-pdf-pages',
        icon: Files,
        desc: 'Clone and duplicate specific pages anywhere inside your PDF file.',
        category: 'Organize',
        action: 'duplicate_pages',
        requiresDoc: true,
        prompt: 'Duplicate pages inside this PDF document.',
      },
    ],
  },
  {
    id: 'convert',
    name: 'Convert',
    icon: Sparkles,
    color: 'text-cyan-600 dark:text-cyan-400',
    bgColor: 'bg-cyan-50 dark:bg-cyan-950/50',
    tools: [
      {
        id: 'pdf-to-word',
        name: 'PDF → Word',
        title: 'PDF to Word Converter',
        path: '/pdf-to-word',
        icon: FileText,
        desc: 'Convert PDF documents into fully editable Microsoft Word (.doc, .docx) files.',
        category: 'Convert',
        action: 'pdf_to_word',
        requiresDoc: true,
        prompt: 'Convert this PDF document to an editable Word file.',
      },
      {
        id: 'pdf-to-excel',
        name: 'PDF → Excel',
        title: 'PDF to Excel Converter',
        path: '/pdf-to-excel',
        icon: FileSpreadsheet,
        desc: 'Extract financial tables and structured data directly into Excel (.xlsx) spreadsheets.',
        category: 'Convert',
        action: 'pdf_to_excel',
        requiresDoc: true,
        prompt: 'Extract all tables from this PDF into an Excel spreadsheet.',
      },
      {
        id: 'pdf-to-powerpoint',
        name: 'PDF → PowerPoint',
        title: 'PDF to PowerPoint Converter',
        path: '/pdf-to-powerpoint',
        icon: Presentation,
        desc: 'Turn PDF slides and presentation decks into editable PowerPoint (.pptx) files.',
        category: 'Convert',
        action: 'pdf_to_ppt',
        requiresDoc: true,
        prompt: 'Convert this PDF presentation into PowerPoint slides.',
      },
      {
        id: 'pdf-to-jpg',
        name: 'PDF → JPG',
        title: 'PDF to JPG Converter',
        path: '/pdf-to-jpg',
        icon: Image,
        desc: 'Convert PDF pages into high-resolution JPG images for easy viewing and sharing.',
        category: 'Convert',
        action: 'pdf_to_jpg',
        requiresDoc: true,
        prompt: 'Convert all pages of this PDF to high-quality JPG images.',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF → PNG',
        title: 'PDF to PNG Converter',
        path: '/pdf-to-png',
        icon: FileImage,
        desc: 'Export PDF pages as crisp, lossless PNG images with transparent backgrounds.',
        category: 'Convert',
        action: 'pdf_to_png',
        requiresDoc: true,
        prompt: 'Export pages from this PDF to high-resolution PNG images.',
      },
      {
        id: 'word-to-pdf',
        name: 'Word → PDF',
        title: 'Word to PDF Converter',
        path: '/word-to-pdf',
        icon: FileUp,
        desc: 'Convert Microsoft Word (.doc, .docx) documents into standard, printer-ready PDFs.',
        category: 'Convert',
        action: 'word_to_pdf',
        requiresDoc: false,
        prompt: 'Convert Word document to PDF format.',
      },
      {
        id: 'excel-to-pdf',
        name: 'Excel → PDF',
        title: 'Excel to PDF Converter',
        path: '/excel-to-pdf',
        icon: Table,
        desc: 'Transform Excel spreadsheets (.xlsx, .xls) into cleanly formatted PDF reports.',
        category: 'Convert',
        action: 'excel_to_pdf',
        requiresDoc: false,
        prompt: 'Convert Excel spreadsheet to PDF document.',
      },
      {
        id: 'powerpoint-to-pdf',
        name: 'PPT → PDF',
        title: 'PowerPoint to PDF Converter',
        path: '/powerpoint-to-pdf',
        icon: SlidersHorizontal,
        desc: 'Convert PowerPoint slide presentations (.ppt, .pptx) into standard PDF documents.',
        category: 'Convert',
        action: 'ppt_to_pdf',
        requiresDoc: false,
        prompt: 'Convert PowerPoint presentation to PDF format.',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG → PDF',
        title: 'JPG to PDF Converter',
        path: '/jpg-to-pdf',
        icon: Upload,
        desc: 'Package JPG and JPEG photos, receipts, or scans into a single, unified PDF file.',
        category: 'Convert',
        action: 'jpg_to_pdf',
        requiresDoc: false,
        prompt: 'Convert JPG images into a single PDF document.',
      },
      {
        id: 'html-to-pdf',
        name: 'HTML → PDF',
        title: 'HTML to PDF Converter',
        path: '/html-to-pdf',
        icon: Globe,
        desc: 'Render and convert live web pages, articles, and HTML code into downloadable PDFs.',
        category: 'Convert',
        action: 'html_to_pdf',
        requiresDoc: false,
        prompt: 'Convert HTML or webpage URL to PDF.',
      },
    ],
  },
  {
    id: 'optimize',
    name: 'Optimize',
    icon: Minimize2,
    color: 'text-amber-500 dark:text-amber-400',
    bgColor: 'bg-amber-50 dark:bg-amber-950/50',
    tools: [
      {
        id: 'compress-pdf',
        name: 'Compress PDF',
        title: 'Compress PDF',
        path: '/compress-pdf',
        icon: Minimize2,
        desc: 'Shrink PDF file size substantially while maintaining maximum visual quality.',
        category: 'Optimize',
        action: 'compress',
        requiresDoc: true,
        prompt: 'Compress and optimize this PDF document to reduce file size.',
      },
      {
        id: 'repair-pdf',
        name: 'Repair PDF',
        title: 'Repair PDF',
        path: '/repair-pdf',
        icon: Wrench,
        desc: 'Inspect and fix damaged, unreadable, or corrupted PDF cross-reference tables.',
        category: 'Optimize',
        action: 'repair',
        requiresDoc: true,
        prompt: 'Repair damaged PDF structure and restore file integrity.',
      },
      {
        id: 'flatten-pdf',
        name: 'Flatten PDF',
        title: 'Flatten PDF',
        path: '/flatten-pdf',
        icon: Layers,
        desc: 'Merge form fields, layers, and annotations directly into the permanent PDF page stream.',
        category: 'Optimize',
        action: 'flatten',
        requiresDoc: true,
        prompt: 'Flatten all annotations, form fields, and layers in this PDF.',
      },
      {
        id: 'pdf-to-pdfa',
        name: 'Convert to PDF/A',
        title: 'Convert to PDF/A',
        path: '/pdf-to-pdfa',
        icon: Archive,
        desc: 'Convert standard PDFs to ISO 19005 compliant PDF/A for long-term legal archiving.',
        category: 'Optimize',
        action: 'pdf_to_pdfa',
        requiresDoc: true,
        prompt: 'Convert this PDF to compliant PDF/A archive format.',
      },
    ],
  },
  {
    id: 'edit',
    name: 'Edit',
    icon: Edit3,
    color: 'text-blue-500 dark:text-blue-400',
    bgColor: 'bg-blue-50 dark:bg-blue-950/50',
    tools: [
      {
        id: 'add-text-to-pdf',
        name: 'Add text',
        title: 'Add Text to PDF',
        path: '/add-text-to-pdf',
        icon: Type,
        desc: 'Insert custom text, headings, notes, or descriptions anywhere on your PDF canvas.',
        category: 'Edit',
        action: 'add_text',
        requiresDoc: true,
        prompt: 'Add custom text overlays to this PDF document.',
      },
      {
        id: 'edit-pdf-text',
        name: 'Edit text',
        title: 'Edit PDF Text',
        path: '/edit-pdf-text',
        icon: Edit3,
        desc: 'Detect and modify existing text content using in-browser OCR intelligence.',
        category: 'Edit',
        action: 'edit_text',
        requiresDoc: true,
        prompt: 'Recognize and edit text layers in this PDF file.',
      },
      {
        id: 'add-images-to-pdf',
        name: 'Add images',
        title: 'Add Images to PDF',
        path: '/add-images-to-pdf',
        icon: ImagePlus,
        desc: 'Place photos, company logos, stamps, and icons anywhere across your PDF pages.',
        category: 'Edit',
        action: 'add_images',
        requiresDoc: true,
        prompt: 'Insert and position images inside this PDF.',
      },
      {
        id: 'draw-on-pdf',
        name: 'Draw',
        title: 'Draw on PDF',
        path: '/draw-on-pdf',
        icon: PenTool,
        desc: 'Freehand sketch, underline, circle, or draw diagrams directly on your document.',
        category: 'Edit',
        action: 'draw',
        requiresDoc: true,
        prompt: 'Freehand sketch and draw markup on this PDF.',
      },
      {
        id: 'highlight-pdf',
        name: 'Highlight',
        title: 'Highlight PDF',
        path: '/highlight-pdf',
        icon: Highlighter,
        desc: 'Highlight important lines and paragraphs with bright, translucent marker strokes.',
        category: 'Edit',
        action: 'highlight',
        requiresDoc: true,
        prompt: 'Highlight key sections of this PDF document.',
      },
      {
        id: 'annotate-pdf',
        name: 'Annotate',
        title: 'Annotate PDF',
        path: '/annotate-pdf',
        icon: MessageSquare,
        desc: 'Attach review comments, sticky notes, and collaborative feedback to your PDF.',
        category: 'Edit',
        action: 'annotate',
        requiresDoc: true,
        prompt: 'Annotate this PDF with comments and review notes.',
      },
      {
        id: 'whiteout-pdf',
        name: 'Whiteout',
        title: 'Whiteout PDF',
        path: '/whiteout-pdf',
        icon: Square,
        desc: 'Conceal unwanted text, errors, or sensitive areas with opaque whiteout blocks.',
        category: 'Edit',
        action: 'whiteout',
        requiresDoc: true,
        prompt: 'Cover and whiteout selected areas on this PDF.',
      },
      {
        id: 'watermark-pdf',
        name: 'Watermark',
        title: 'Watermark PDF',
        path: '/watermark-pdf',
        icon: Stamp,
        desc: 'Stamp custom text watermarks (CONFIDENTIAL, DRAFT, copyright) across every page.',
        category: 'Edit',
        action: 'watermark',
        requiresDoc: true,
        prompt: 'Stamp a custom watermark across all pages of this PDF.',
      },
      {
        id: 'page-numbers-pdf',
        name: 'Page numbers',
        title: 'Add Page Numbers to PDF',
        path: '/page-numbers-pdf',
        icon: Hash,
        desc: 'Apply clean, sequential page numbering (Page 1 of N) automatically to your document.',
        category: 'Edit',
        action: 'page_numbers',
        requiresDoc: true,
        prompt: 'Add page numbers across this PDF document.',
      },
      {
        id: 'headers-footers-pdf',
        name: 'Headers/footers',
        title: 'Headers and Footers for PDF',
        path: '/headers-footers-pdf',
        icon: PanelTop,
        desc: 'Insert custom headers, footers, dates, and author information across all pages.',
        category: 'Edit',
        action: 'headers_footers',
        requiresDoc: true,
        prompt: 'Add header and footer labels to this PDF document.',
      },
    ],
  },
  {
    id: 'security',
    name: 'Security',
    icon: ShieldCheck,
    color: 'text-emerald-500 dark:text-emerald-400',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/50',
    tools: [
      {
        id: 'password-protect-pdf',
        name: 'Password protect',
        title: 'Password Protect PDF',
        path: '/password-protect-pdf',
        icon: Lock,
        desc: 'Encrypt your PDF with strong AES-256 passwords to prevent unauthorized access.',
        category: 'Security',
        action: 'password_protect',
        requiresDoc: true,
        prompt: 'Encrypt this PDF document with password security.',
      },
      {
        id: 'unlock-pdf',
        name: 'Remove password',
        title: 'Unlock PDF',
        path: '/unlock-pdf',
        icon: Unlock,
        desc: 'Remove password restrictions and decrypt secured PDFs for unrestricted editing.',
        category: 'Security',
        action: 'remove_password',
        requiresDoc: true,
        prompt: 'Unlock and remove password permissions from this PDF.',
      },
      {
        id: 'redact-pdf',
        name: 'Redact',
        title: 'Redact PDF',
        path: '/redact-pdf',
        icon: EyeOff,
        desc: 'Permanently blackout and sanitize sensitive personal, financial, or confidential data.',
        category: 'Security',
        action: 'redact',
        requiresDoc: true,
        prompt: 'Redact and permanently sanitize sensitive information in this PDF.',
      },
      {
        id: 'remove-pdf-metadata',
        name: 'Remove metadata',
        title: 'Remove PDF Metadata',
        path: '/remove-pdf-metadata',
        icon: ShieldAlert,
        desc: 'Strip hidden author names, creation timestamps, GPS data, and edit histories.',
        category: 'Security',
        action: 'remove_metadata',
        requiresDoc: true,
        prompt: 'Strip all metadata and author history from this PDF file.',
      },
    ],
  },
  {
    id: 'forms',
    name: 'Forms',
    icon: CheckSquare,
    color: 'text-violet-500 dark:text-violet-400',
    bgColor: 'bg-violet-50 dark:bg-violet-950/50',
    tools: [
      {
        id: 'fill-pdf',
        name: 'Fill PDF',
        title: 'Fill PDF Forms',
        path: '/fill-pdf',
        icon: FileCheck2,
        desc: 'Complete and fill out interactive PDF AcroForms, text inputs, and checkboxes.',
        category: 'Forms',
        action: 'fill_pdf',
        requiresDoc: true,
        prompt: 'Fill out interactive form fields in this PDF.',
      },
      {
        id: 'create-pdf-form',
        name: 'Create form fields',
        title: 'Create PDF Form Fields',
        path: '/create-pdf-form',
        icon: CheckSquare,
        desc: 'Design and embed fillable text fields, checkboxes, dropdowns, and buttons in your PDF.',
        category: 'Forms',
        action: 'create_form_fields',
        requiresDoc: true,
        prompt: 'Create and add fillable form fields to this PDF.',
      },
      {
        id: 'sign-pdf',
        name: 'Sign PDF',
        title: 'Sign PDF Document',
        path: '/sign-pdf',
        icon: PenLine,
        desc: 'Draw, type, or upload legally-binding electronic signatures and place them on pages.',
        category: 'Forms',
        action: 'sign',
        requiresDoc: true,
        prompt: 'Sign this PDF document with an electronic signature.',
      },
      {
        id: 'request-pdf-signature',
        name: 'Request signature',
        title: 'Request PDF Signature',
        path: '/request-pdf-signature',
        icon: Send,
        desc: 'Send documents directly to recipients and collect legally verified e-signatures.',
        category: 'Forms',
        action: 'request_signature',
        requiresDoc: true,
        prompt: 'Prepare and request signatures on this PDF document.',
      },
    ],
  },
];

export const ALL_TOOLS = CATEGORIES.flatMap((c) => c.tools);

export function getToolByPath(path) {
  return ALL_TOOLS.find((t) => t.path === path);
}

export function getToolById(id) {
  return ALL_TOOLS.find((t) => t.id === id);
}
